using System.IO;
using System.Xml.Linq;
using DDEX_Deserialiser.AutoGenerated;

namespace DDEX_Deserialiser
{
	public class DDEX
	{
		public NewReleaseMessage Root { get; private set; }

		public DDEX(string sourceFilePath)
			: this(XDocument.Load(sourceFilePath))
		{
		}

		public DDEX(Stream stream)
			: this(XDocument.Load(stream))
		{
		}

		public DDEX(XDocument doc)
		{
			Root = new NewReleaseMessage(doc.Root);
		}
	}
}
