using System.Reflection;

[assembly: AssemblyTitle("DDEX-Deserialiser")]
[assembly: AssemblyProduct("DDEX-Deserialiser")]
[assembly: AssemblyCompany("7digital")]
[assembly: AssemblyDescription("A DDEX XML batch deserialiser generated by 7digital/XsdToObject")]
[assembly: AssemblyVersion("1.1.1.1")]
[assembly: AssemblyFileVersion("1.1.1.1")]
