using System.Linq;
using DDEX_Deserialiser.AutoGenerated;
using NUnit.Framework;

namespace Deserialiser.Unit.Tests
{
    [TestFixture]
    public class ImageTests : BigDdexXml
    {
        private Image GetImage()
        {
            return ddex.root.ResourceList.Images.Single();
        }

        [Test]
        public void Should_image_be_a_cover_image()
        {
            Assert.That(GetImage().ImageType, Is.EqualTo("FrontCoverImage"));
        }

    }
}
